[config]
model = "groq/groq/compound"
fallback_models = ["groq/groq/compound-mini"]
custom_model_max_tokens = 70000

[github_action_config]
auto_review = true
auto_describe = false
auto_improve = true
pr_actions = ["opened", "reopened", "ready_for_review", "review_requested", "synchronize"]

[pr_reviewer]
require_score_review = true
require_security_review = true
require_todo_scan = true

[pr_code_suggestions]
commitable_code_suggestions = true
