name: PR Agent

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  issue_comment:
    types: [created, edited]

permissions:
  pull-requests: write
  issues: write
  contents: read

jobs:
  code_review:
    runs-on: ubuntu-latest
    if: >
      (github.event_name == 'pull_request' && contains(fromJson('["OWNER", "COLLABORATOR"]'), github.event.pull_request.author_association)) ||
      (github.event_name == 'issue_comment' && contains(fromJson('["OWNER", "COLLABORATOR"]'), github.event.comment.author_association))
    steps:
      - name: PR Agent action step
        uses: the-pr-agent/pr-agent@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          PR_AGENT__CONFIG__MODEL: "groq/llama3-70b-8192"
          PR_AGENT__CONFIG__FALLBACK_MODELS: "groq/llama3-8b-8192"
