name: PR Agent

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  issue_comment:
    types: [created, edited]

permissions:
  pull-requests: write
  issues: write
  contents: read

jobs:
  code_review:
    runs-on: ubuntu-latest
    if: >
      (github.event_name == 'pull_request' && contains(fromJson('["OWNER", "COLLABORATOR"]'), github.event.pull_request.author_association)) ||
      (github.event_name == 'issue_comment' && contains(fromJson('["OWNER", "COLLABORATOR"]'), github.event.comment.author_association))
    steps:
      - name: PR Agent action step
        uses: the-pr-agent/pr-agent@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          config.model: "groq/llama3-70b-8192"
          config.fallback_models: '["groq/llama3-8b-8192"]'
          config.custom_model_max_tokens: "8192"
          github_action_config.auto_review: "true"
          github_action_config.auto_describe: "true"
          github_action_config.pr_actions: '["opened", "reopened", "ready_for_review", "review_requested", "synchronize"]'
